Login: #登录模块
  login: # 登录接口
    path: /account/sLogin # 登录路径
    method: POST
  loginout: # 退出接口
    path: "xxxxx"
    method: POST

Shop: # 商品管理
  query: # 列出商品
    path: /shopping/myShop
    method: GET
  update: # 修改商品信息
    path: /shopping/updatemyshop
    method: POST
  file_upload: # 图片上传
    path: /file
    method: POST
